# frozen_string_literal: true

source "https://rubygems.org"

gem "pronto", git: "https://github.com/prontolabs/pronto", branch: "master"
gem "pronto-rubocop", git: "https://github.com/prontolabs/pronto-rubocop", branch: "master"
